### ISSUE TITLE
anyone is maintaining this project? 

### ISSUE THREAD

**Issue by hixichen** [jackc/go_db_bench#3]
I really like this project and it helps us to make decision when compare to different postgresql wappger. 

But, it seems pg has v8 and there is no update since 3 years ago. 

Anyone is actually working on this?

**Comment by jackc** [comment]
I update it occasionally when I need to. But most of what I do is comparing one version of pgx against another so I haven't had to do much lately. I'd be happy to include the newer go-pg, but figuring out what has changed in 5 major versions hasn't been a priority for me.

**Comment by jackc** [comment]
FYI, I just updated this to the prerelease pgx v4, pq v1.1.1, and pg v8.
